if GetLocale() ~= "deDE" then return end

Loc = Loc or {
    -- Klassen
    ["warrior"] = "Krieger",
    ["hunter"] = "Jäger",
    ["paladin"] = "Paladin",
    ["mage"] = "Magier",
    ["priest"] = "Priester",
    ["warlock"] = "Hexenmeister",
    ["shaman"] = "Schamane",
    ["druid"] = "Druide",
    ["rogue"] = "Schurke",
    -- Jäger
    --p1
    ["heart of the lion"] = "Herz des Löwen",
    ["master marksman"] = "Meisterschütze",
    ["lone wolf"] = "Einsamer Wolf",
    ["cobra strikes"] = "Kobraschläge",
    ["kill command"] = "Tötungsbefehl",
    ["sniper training"] = "Scharfschützentraining",
    ["serpent spread"] = "Schlangenschwarm",
    ["flanking strike"] = "Flankenangriff",
    ["beast mastery"] = "Tierherrschaft",
    ["chimera shot"] = "Schimärenschuss",
    ["explosive shot"] = "Explosivschuss",
    ["carve"] = "Schnitzen",
    --p2
    ["dual wield specialization"] = "Beidhändigkeits-Spezialisierung",
    ["expose weakness"] = "Schwäche aufdecken",
    ["invigoration"] = "Belebung",
    ["steady shot"] = "Zuverlässiger Schuss",
    ["trap launcher"] = "Fallenwerfer",
    ["melee specialist"] = "Nahkampfspezialist",
    -- Krieger
    --p1
    ["flagellation"] = "Geißelung",
    ["blood frenzy"] = "Blutraserei",
    ["raging blow"] = "Tobender Schlag",
    ["warbringer"] = "Kriegsbringer",
    ["furious thunder"] = "Wütender Donner",
    ["consumed by rage"] = "Von Wut verzehrt",
    ["frenzied assault"] = "Rasender Angriff",
    ["victory rush"] = "Siegesrausch",
    ["endless rage"] = "Endlose Wut",
    ["devastate"] = "Verwüsten",
    ["single-minded fury"] = "Entschlossene Wut",
    ["quick strike"] = "Schneller Schlag",
    --p2
    ["focused rage"] = "Fokussierte Wut",
    ["intervene"] = "Einschreiten",
    ["rallying cry"] = "Anspornender Schrei",
    ["enraged regeneration"] = "Wütende Regeneration",
    ["blood surge"] = "Blutwallung",
    ["precise timing"] = "Präzises Timing",
    -- Paladin
    --p1
    ["seal of martyrdom"] = "Siegel des Märtyrertums",
    ["divine storm"] = "Göttlicher Sturm",
    ["horn of lordaeron"] = "Horn von Lordaeron",
    ["aegis"] = "Ägis",
    ["divine sacrifice"] = "Göttliches Opfer",
    ["inspiration exemplar"] = "Inspirierendes Vorbild",
    ["avenger's shield"] = "Schild des Rächers",
    ["exorcist"] = "Exorzist",
    ["rebuke"] = "Zurechtweisung",
    ["beacon of light"] = "Lichtsignal",
    ["crusader strike"] = "Kreuzfahrerschlag",
    ["hand of reckoning"] = "Hand der Abrechnung",
    --p2
    ["enlightened judgements"] = "Erleuchtete Urteile",
    ["guarded by the light"] = "Vom Licht behütet",
    ["sacred shield"] = "Heiliger Schild",
    ["the art of war"] = "Die Kunst des Krieges",
    ["infusion of light"] = "Lichtinfusion",
    ["sheath of light"] = "Lichtscheide",
    -- Magier
    --p1
    ["burnout"] = "Ausgebrannt",
    ["fingers of frost"] = "Eisige Finger",
    ["regeneration"] = "Regeneration",
    ["enlightenment"] = "Erleuchtung",
    ["icy veins"] = "Eisige Adern",
    ["arcane surge"] = "Arkanschub",
    ["mass regeneration"] = "Massenregeneration",
    ["living flame"] = "Lebendige Flamme",
    ["rewind time"] = "Zeit zurückspulen",
    ["living bomb"] = "Lebende Bombe",
    ["arcane blast"] = "Arkanschlag",
    ["ice lance"] = "Eislanze",
    --p2
    ["spellfrost bolt"] = "Zauberfrostbolzen",
    ["chronostatic preservation"] = "Chronostatische Bewahrung",
    ["hot streak"] = "Heiße Serie",
    ["frostfire bolt"] = "Frostfeuerblitz",
    ["brain freeze"] = "Gehirnfrost",
    ["spell power"] = "Zaubermacht",
    ["missile barrage"] = "Raketensalve",
    -- Priester
    --p1
    ["void plague"] = "Leerenpest",
    ["serendipity"] = "Serendipität",
    ["strength of soul"] = "Seelenstärke",
    ["twisted faith"] = "Verdrehter Glaube",
    ["power word: barrier"] = "Machtwort: Barriere",
    ["shared pain"] = "Geteiltes Leid",
    ["homunculi"] = "Homunkuli",
    ["prayer of mending"] = "Gebet der Besserung",
    ["penance"] = "Buße",
    ["mind sear"] = "Gedankenschinden",
    ["circle of healing"] = "Kreis der Heilung",
    ["shadow word: death"] = "Schattenwort: Tod",
    --p2
    ["dispersion"] = "Dispersion",
    ["divine aegis"] = "Göttliche Aegis",
    ["empowered renew"] = "Machtvolle Erneuerung",
    ["renewed hope"] = "Erneuerte Hoffnung",
    ["mind spike"] = "Gedankenspieß",
    ["shadowfriend"] = "Schattenfreund",
    ["powerword: barrier"] = "Machtwort: Barriere",
    ["pain suppression"] = "Schmerzunterdrückung",
    ["spirit of the redeemer"] = "Geist des Erlösers",
    ["surge of light"] = "Lichtschwall",
    ["despair"] = "Verzweiflung",
    ["void zone"] = "Leerenzone",
    -- Hexenmeister
    --p1
    ["lake of fire"] = "Feuersee",
    ["master channeler"] = "Meisterkanalisierer",
    ["soul siphon"] = "Seelensog",
    ["demonic tactics"] = "Dämonische Taktiken",
    ["everlasting affliction"] = "Ewige Pein",
    ["incinerate"] = "Verbrennen",
    ["demonic grace"] = "Dämonische Anmut",
    ["demonic pact"] = "Dämonischer Pakt",
    ["metamorphosis"] = "Metamorphose",
    ["shadow bolt volley"] = "Schattenblitzsalve",
    ["chaos bolt"] = "Chaosblitz",
    ["haunt"] = "Heimsuchung",
    --p2
    ["dance of the wicked"] = "Tanz der Verdammten",
    ["shadowflame"] = "Schattenflamme",
    ["grimoire of synergy"] = "Lehrbuch der Synergie",
    ["shadow and flame"] = "Schatten und Flamme",
    ["invocation"] = "Beschwörung",
    ["demonic knowledge"] = "Dämonisches Wissen",
    -- Schamane
    --p1
    ["dual wield specialization"] = "Spezialisierung auf beidhändigen Kampf",
    ["shield mastery"] = "Schildbeherrschung",
    ["overload"] = "Überladung",
    ["healing rain"] = "Heilender Regen",
    ["ancestral guidance"] = "Ahnenführung",
    ["earth shield"] = "Erdschild",
    ["way of earth"] = "Weg der Erde",
    ["shamanistic rage"] = "Schamanistische Wut",
    ["water shield"] = "Wasserschild",
    ["lava burst"] = "Lavastoß",
    ["lava lash"] = "Lavapeitsche",
    ["molten blast"] = "Geschmolzener Schlag",
    --p2
    ["decoy totem"] = "Lockvogeltotem",
    ["spirit of the alpha"] = "Geist des Alphas",
    ["power surge"] = "Energieschub",
    ["maelstrom weapon"] = "Waffe des Mahlstroms",
    ["fire nova"] = "Feuernova",
    ["ancestral awakening"] = "Ahnenweckung",
    ["two-handed mastery"] = "Meisterschaft im Zweihandkampf",
    -- Druide
    --p1
    ["living seed"] = "Lebendiger Samen",
    ["wild strikes"] = "Wilde Schläge",
    ["fury of stormrage"] = "Sturmgrimms Wut",
    ["survival of the fittest"] = "Überleben des Stärkeren",
    ["starsurge"] = "Sternensog",
    ["lifebloom"] = "Blühendes Leben",
    ["skull bash"] = "Schädelstoß",
    ["savage roar"] = "Wildes Brüllen",
    ["sunfire"] = "Sonnenfeuer",
    ["lacerate"] = "Aufschlitzen",
    ["wild growth"] = "Wildwuchs",
    ["mangle"] = "Zerfleischen",
    --p2
    ["berserk"] = "Berserker",
    ["dreamstate"] = "Traumzustand",
    ["survival instincts"] = "Überlebensinstinkte",
    ["eclipse"] = "Finsternis",
    ["nourish"] = "Nähren",
    ["king of the jungle"] = "König des Dschungels",
    -- Schurke
    --p1
    ["deadly brew"] = "Tödlicher Trank",
    ["just a flesh wound"] = "Nur eine Fleischwunde",
    ["quick draw"] = "Schneller Zug",
    ["slaughter from the shadows"] = "Schlachten aus den Schatten",
    ["between the eyes"] = "Zwischen den Augen",
    ["blade dance"] = "Klingentanz",
    ["envenom"] = "Vergiften",
    ["mutilate"] = "Verstümmeln",
    ["shadowstrike"] = "Schattenschlag",
    ["saber slash"] = "Säbelhieb",
    ["shiv"] = "Taschendolch",
    ["main gauche"] = "Parierdolch",
    --p2
    ["rolling with the punches"] = "Mit den Schlägen rollen",
    ["shadowstep"] = "Schattenschritt",
    ["master of subtlety"] = "Meister der Subtilität",
    ["shuriken toss"] = "Shurikenwurf",
    ["poisoned knife"] = "Vergiftetes Messer",
    ["waylay"] = "Hinterhalt",
}
